server:
    port: 9000
    servlet:
        context-path: ${CONTEXT_PATH:/api/v1}
spring:
    application:
        name: ci_cd
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ${SPRING_DATASOURCE_PASSWORD}
        url: jdbc:mysql://localhost:3306/ci-cd?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
        username: ${SPRING_DATASOURCE_USERNAME}
    jackson:
        default-property-inclusion: non_null
        serialization:
            fail_on_empty_beans: false
    flyway:
        password: ${SPRING_DATASOURCE_PASSWORD}
        url: jdbc:mysql://localhost:3306/ci-cd?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
        user: ${SPRING_DATASOURCE_USERNAME}
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        show-sql: ${JPA_SHOW_SQL:false}