name: Continuous Integration whith Github

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v3.10.0

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      #if: github.event_name != 'pull_request'
      #uses: docker/login-action@v3
      #with:
      #  username: ${{ secrets.DOCKER_USERNAME }}
      #  password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Verify Docker login
      run: docker info

    - name: Setup Java JDK
      uses: actions/setup-java@v4.7.0
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Run Tests and Package Application
      env:
        SPRING_PROFILES_ACTIVE: test
      run: mvn clean verify

    - name: Build CI_CD Jar
      #working-directory: ./
      run: mvn clean package -DskipTests

    #- name: Docker Compose Build
    #  working-directory: ./
    #  run: docker compose build

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd:latest .

    - name: List Docker Images
      run: docker images

    - name: Push to Dockerhub Container Registry
      run: |
           docker tag ${{ secrets.DOCKER_USERNAME }}/cicd:latest ${{ secrets.DOCKER_USERNAME }}/cicd:${{ github.run_id }}
           docker tag ${{ secrets.DOCKER_USERNAME }}/cicd:latest ${{ secrets.DOCKER_USERNAME }}/cicd:latest
           docker push ${{ secrets.DOCKER_USERNAME }}/cicd:${{ github.run_id }}
           docker push ${{ secrets.DOCKER_USERNAME }}/cicd:latest