name: Continuous Integration whith Github

on:
  schedule:
    - cron: '44 1 * * *'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.0.5
        with:
          cosign-release: 'v2.0.2'

      # Workaround: https://github.com/docker/build-push-action
      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3.10.0

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Login to Docker Hub ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      #https://github.com/marketplace/actions/setup-java-jdk    
      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.0
        with:
          # The Java version to make available on the path. Takes a whole or semver Java version, or 1.x syntax (e.g. 1.8 => Java 8.x). Early access versions can be specified in the form of e.g. 14-ea, 14.0.0-ea, or 14.0.0-ea.28
          java-version: '21'
          distribution: 'adopt'
        
      - name: Build CI_CD Jar
        working-directory: ./
        run: mvn clean package
        
      - name: Docker Compose Build
        working-directory: ./
        run: docker-compose build
        
      - name: Push to Dockerhub Container Registry
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/cicd:latest ${{ secrets.DOCKER_USERNAME }}/cicd:${{ github.run_id }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/cicd:latest ${{ secrets.DOCKER_USERNAME }}/cicd:latest
